name: ${project.name}
main: ${project.mainClass}
version: ${project.version}

description: ${project.description}
author: ${project.author}
website: ${project.url}

commands:
  lockweather:
    aliases: [weatherlock]
    description: Allows to see locked worlds, reload config and lock and unlock the weather in the sender's world